### ISSUE TITLE
Crash with Dynamic Stealth

### ISSUE THREAD

**Issue by Versimno** [The-Fireplace-Minecraft-Mods/TickDynamic#30]
Opening a world with the latest version of Tick Dynamic ( version 1.12.2-1.0.1) with Dynamic Stealth version 1.12.2.0.20 or above, crashes the game.

Here's the crash log: [crash-2019-01-06_23.30.25-server](https://paste.ubuntu.com/p/BZK9GKxfRS/)

And here's the latest log file: [debug.log](https://paste.ubuntu.com/p/kbMdmT2Xr9/)

I'm using Forge version 1.12.2-14.23.5.2796

This has already been reported to the creator of Dynamic Stealth, but they said to post it here. Laike-Endaril/Dynamic-Stealth#10

**Comment by Laike-Endaril** [comment]
Hey, I'm the DS dev.  I just now finished the thing I was working on at the time and looked into this a bit further.  Turns out I was right on the money....details as follows:

In package: src/main/java/com/wildex999/tickdynamic/listinject
In class: ListManager
On line: 428
Direct link: [https://github.com/The-Fireplace-Minecraft-Mods/TickDynamic/blob/17fa4ef5c3cfd88ed322d08281650ae0f7e86b6e/src/main/java/com/wildex999/tickdynamic/listinject/ListManager.java#L428](https://github.com/The-Fireplace-Minecraft-Mods/TickDynamic/blob/17fa4ef5c3cfd88ed322d08281650ae0f7e86b6e/src/main/java/com/wildex999/tickdynamic/listinject/ListManager.java#L428)

This one has nothing to do with my own mod, so I'll be closing the issue over on my tracker.  Good luck! XD

**Comment by Sunconure11** [comment]
@laike-endaril TickDynamic is no longer maintained. Perhaps you could take over development if feasible?

**Comment by Sunconure11** [comment]
At the very least, maybe some pulls or something

**Comment by Sunconure11** [comment]
At the very least, maybe some pulls or something

**Comment by Laike-Endaril** [comment]
@Sunconure11 Sorry, but I will not be taking over this project.  I won't be doing PRs for it either.  I have a massive TODO list already for my own stuff.

**Comment by Laike-Endaril** [comment]
They should let you use reactions on auto-generated messages, but oh well, I'll put it here :+1:
