### ISSUE TITLE
"Your copy of Tick Dynamic does not appear to be vaild. Please click here and download a fresh copy. if you did download it from that link, please report this error on the issue tracker." self explanetory.

### ISSUE THREAD

**Issue by YayJohn** [The-Fireplace-Minecraft-Mods/TickDynamic#44]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * For any issue, providing your fml-client-latest.log or fml-server-latest.log can be very helpful. If you have one of these, please paste it to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com/) and link it here.
 * If you crashed, please paste the crash log to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com/) and link it here.

**Comment by ScienceDrummer** [comment]
Getting that one occasional too.

**Comment by HydrogenC** [comment]
Getting that one every time.

**Comment by CoolMouthHat** [comment]
this error appeared after installign optifine on a custom pack. more info available if needed.

**Comment by YayJohn** [comment]
I also had optifine installed, It was on a certain modpack, I think it was
project ozone 3, not sure tho.

**Comment by Water-Moon** [comment]
I also got this notice :(
![图片](https://user-images.githubusercontent.com/43123946/66438251-2bf3bb00-e9fa-11e9-9969-82cff1ee1228.png)

**Comment by QazCetelic** [comment]
I also get that

**Comment by thisischrys** [comment]
I checked: the md5sum is identical to one I have that does NOT give the error. Filename is different though:  could this be the issue? It shouldn't matter in Java unless the code does something weird.
Is this mod still alive even? This seems to have been open without replies for a long time.

**Comment by Quest79** [comment]
Why directly tell us to post this here then ignore it for a year?

**Comment by Water-Moon** [comment]
This mod seems to have died, or at least... partially archived?

For this problem particularly, I was looking into the code, and it looks like the code is just checking the FMLFingerprintViolationEvent. It looks like the fingerprint given to the FML is not the same as the mod itself - the author might forget to update the annotation while bumping versions... (oops)

It looks for now at least we can safely ignore this "invalid" notification because it's the author's operation that is invalid, not the file we downloaded ;)

**Comment by Macleykun** [comment]
I asked The_fireplace on forge if he can look into this. He'll do it when he get's the chance.
